package postgres

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"time"

	"ispilolite/internal/models"
	"ispilolite/pkg/database"
)

type quotationRepository struct { dbReader, dbWriter *sql.DB }
func NewQuotationRepository() *quotationRepository { return &quotationRepository{dbReader:database.GetReader(),dbWriter:database.GetWriter()} }

func (r *quotationRepository) NextQuotationNumber(at time.Time)(string,error){var sequence int64;if err:=r.dbWriter.QueryRow(`SELECT nextval('quotation_number_seq')`).Scan(&sequence);err!=nil{return "",err};return fmt.Sprintf("QT-%04d-%02d-%05d",at.Year(),int(at.Month()),sequence),nil}
func (r *quotationRepository) PublicCodeExists(code string)(bool,error){var exists bool;err:=r.dbReader.QueryRow(`SELECT EXISTS(SELECT 1 FROM quotations WHERE public_code=$1)`,code).Scan(&exists);return exists,err}

func (r *quotationRepository) FinalizeQuotation(q *models.Quotation) error {
	tx,err:=r.dbWriter.Begin();if err!=nil{return err};defer tx.Rollback()
	payment,err:=json.Marshal(q.PaymentDetails);if err!=nil{return err};terms,err:=json.Marshal(q.Terms);if err!=nil{return err}
	_,err=tx.Exec(`INSERT INTO quotations (id,public_code,quotation_number,issuer_id,issuer_role,customer_id,request_id,company_name,company_phone,company_email,company_address,company_logo_url,business_type,customer_name,customer_phone,customer_email,customer_location,currency,subtotal,discount_amount,transport_enabled,transport_amount,tax_enabled,taxable_amount,tax_amount,tax_rate,tax_mode,total_amount,payment_method,payment_details,terms,notes,status,created_at,updated_at,finalized_at,expires_at) VALUES ($1,$2,$3,$4,$5,$6,NULLIF($7,'')::uuid,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37)`,q.ID,q.PublicCode,q.QuotationNumber,q.IssuerID,q.IssuerRole,q.CustomerID,q.RequestID,q.CompanyName,q.CompanyPhone,q.CompanyEmail,q.CompanyAddress,q.CompanyLogoURL,q.BusinessType,q.CustomerName,q.CustomerPhone,q.CustomerEmail,q.CustomerLocation,q.Currency,q.Subtotal,q.DiscountAmount,q.TransportEnabled,q.TransportAmount,q.TaxEnabled,q.TaxableAmount,q.TaxAmount,q.TaxRate,q.TaxMode,q.TotalAmount,q.PaymentMethod,payment,terms,q.Notes,q.Status,q.CreatedAt,q.UpdatedAt,q.FinalizedAt,q.ExpiresAt);if err!=nil{return err}
	for _,item:=range q.Items{_,err=tx.Exec(`INSERT INTO quotation_items (id,quotation_id,item,description,unit_id,unit_name,unit_symbol,quantity,unit_price,gross_amount,discount_type,discount_value,discount_amount,amount,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,item.ID,q.ID,item.Item,item.Description,item.UnitID,item.UnitName,item.UnitSymbol,item.Quantity,item.UnitPrice,item.GrossAmount,item.DiscountType,item.DiscountValue,item.DiscountAmount,item.Amount,item.CreatedAt);if err!=nil{return err}}
	if q.TaxEnabled{_,err=tx.Exec(`INSERT INTO quotation_tax (id,quotation_id,tax_rate_id,rate,calculation_type,taxable_amount,tax_amount) VALUES (gen_random_uuid(),$1,$2,$3,$4,$5,$6)`,q.ID,q.TaxRateID,q.TaxRate,q.TaxMode,q.TaxableAmount,q.TaxAmount);if err!=nil{return err}}
	data,_:=json.Marshal(map[string]interface{}{"quotation_id":q.ID,"public_code":q.PublicCode,"quotation_number":q.QuotationNumber})
	_,err=tx.Exec(`INSERT INTO notifications (id,user_id,type,title,message,data,created_at) VALUES (gen_random_uuid(),$1,'quotation_received','New quotation',$2,$3,now())`,q.CustomerID,"You received quotation "+q.QuotationNumber,data);if err!=nil{return err}
	return tx.Commit()
}

const quotationColumns=`id,public_code,quotation_number,issuer_id,issuer_role,customer_id,COALESCE(request_id::text,''),company_name,company_phone,company_email,company_address,company_logo_url,business_type,customer_name,customer_phone,customer_email,customer_location,currency,subtotal,discount_amount,transport_enabled,transport_amount,tax_enabled,taxable_amount,tax_amount,tax_rate,tax_mode,total_amount,payment_method,payment_details,terms,notes,status,created_at,updated_at,finalized_at,expires_at`
func scanQuotation(row interface{Scan(...interface{})error})(*models.Quotation,error){q:=&models.Quotation{};var payment,terms []byte;err:=row.Scan(&q.ID,&q.PublicCode,&q.QuotationNumber,&q.IssuerID,&q.IssuerRole,&q.CustomerID,&q.RequestID,&q.CompanyName,&q.CompanyPhone,&q.CompanyEmail,&q.CompanyAddress,&q.CompanyLogoURL,&q.BusinessType,&q.CustomerName,&q.CustomerPhone,&q.CustomerEmail,&q.CustomerLocation,&q.Currency,&q.Subtotal,&q.DiscountAmount,&q.TransportEnabled,&q.TransportAmount,&q.TaxEnabled,&q.TaxableAmount,&q.TaxAmount,&q.TaxRate,&q.TaxMode,&q.TotalAmount,&q.PaymentMethod,&payment,&terms,&q.Notes,&q.Status,&q.CreatedAt,&q.UpdatedAt,&q.FinalizedAt,&q.ExpiresAt);if err!=nil{return nil,err};_ = json.Unmarshal(payment,&q.PaymentDetails);_ = json.Unmarshal(terms,&q.Terms);return q,nil}
func (r *quotationRepository) loadItems(q *models.Quotation)error{rows,err:=r.dbReader.Query(`SELECT id,quotation_id,item,description,unit_id,unit_name,unit_symbol,quantity,unit_price,gross_amount,discount_type,discount_value,discount_amount,amount,created_at FROM quotation_items WHERE quotation_id=$1 ORDER BY created_at,id`,q.ID);if err!=nil{return err};defer rows.Close();q.Items=[]*models.QuotationItem{};for rows.Next(){i:=&models.QuotationItem{};if err:=rows.Scan(&i.ID,&i.QuotationID,&i.Item,&i.Description,&i.UnitID,&i.UnitName,&i.UnitSymbol,&i.Quantity,&i.UnitPrice,&i.GrossAmount,&i.DiscountType,&i.DiscountValue,&i.DiscountAmount,&i.Amount,&i.CreatedAt);err!=nil{return err};q.Items=append(q.Items,i)};return rows.Err()}
func (r *quotationRepository) GetQuotationByID(id string)(*models.Quotation,error){q,err:=scanQuotation(r.dbReader.QueryRow(`SELECT `+quotationColumns+` FROM quotations WHERE id=$1`,id));if err!=nil{return nil,err};return q,r.loadItems(q)}
func (r *quotationRepository) GetQuotationByPublicCode(code string)(*models.Quotation,error){q,err:=scanQuotation(r.dbReader.QueryRow(`SELECT `+quotationColumns+` FROM quotations WHERE public_code=$1`,code));if err!=nil{return nil,err};if q.Status=="SENT"{_,_=r.dbWriter.Exec(`UPDATE quotations SET status='VIEWED',updated_at=now() WHERE id=$1`,q.ID);q.Status="VIEWED"};return q,r.loadItems(q)}
func (r *quotationRepository) ListQuotations(userID,role,status string,limit int)([]*models.Quotation,error){field:="customer_id";if role=="isp"||role=="technician"{field="issuer_id"};rows,err:=r.dbReader.Query(`SELECT `+quotationColumns+` FROM quotations WHERE `+field+`=$1 AND ($2='' OR status=$2) ORDER BY created_at DESC LIMIT $3`,userID,status,limit);if err!=nil{return nil,err};defer rows.Close();out:=[]*models.Quotation{};for rows.Next(){q,err:=scanQuotation(rows);if err!=nil{return nil,err};out=append(out,q)};return out,rows.Err()}
func (r *quotationRepository) UpdateQuotationStatus(id,customerID,status string)error{result,err:=r.dbWriter.Exec(`UPDATE quotations SET status=$1,updated_at=now() WHERE id=$2 AND customer_id=$3 AND status IN ('FINALIZED','SENT','VIEWED')`,status,id,customerID);if err!=nil{return err};n,err:=result.RowsAffected();if err!=nil{return err};if n==0{return sql.ErrNoRows};return nil}
func (r *quotationRepository) GetUnit(id,issuerID string)(*models.QuotationUnit,error){u:=&models.QuotationUnit{};err:=r.dbReader.QueryRow(`SELECT id,name,singular_name,plural_name,symbol,is_system FROM quotation_units WHERE id=$1 AND (is_system=true OR issuer_id=$2)`,id,issuerID).Scan(&u.ID,&u.Name,&u.SingularName,&u.PluralName,&u.Symbol,&u.IsSystem);return u,err}
func (r *quotationRepository) ListUnits(issuerID,query string,limit int)([]*models.QuotationUnit,error){rows,err:=r.dbReader.Query(`SELECT id,name,singular_name,plural_name,symbol,is_system FROM quotation_units WHERE (is_system=true OR issuer_id=$1) AND name ILIKE '%'||$2||'%' ORDER BY CASE WHEN lower(name)=lower($2) THEN 0 WHEN name ILIKE $2||'%' THEN 1 ELSE 2 END,name LIMIT $3`,issuerID,query,limit);if err!=nil{return nil,err};defer rows.Close();out:=[]*models.QuotationUnit{};for rows.Next(){u:=&models.QuotationUnit{};if err:=rows.Scan(&u.ID,&u.Name,&u.SingularName,&u.PluralName,&u.Symbol,&u.IsSystem);err!=nil{return nil,err};out=append(out,u)};return out,rows.Err()}
func (r *quotationRepository) CreateUnit(u *models.QuotationUnit,issuerID string)error{_,err:=r.dbWriter.Exec(`INSERT INTO quotation_units (id,name,singular_name,plural_name,symbol,is_system,issuer_id) VALUES ($1,$2,$3,$4,$5,false,$6)`,u.ID,u.Name,u.SingularName,u.PluralName,u.Symbol,issuerID);return err}
func (r *quotationRepository) GetTaxRate(id string)(*models.TaxRate,error){t:=&models.TaxRate{};var err error;if id==""{err=r.dbReader.QueryRow(`SELECT id,name,rate,is_default FROM tax_rates WHERE is_active=true AND is_default=true LIMIT 1`).Scan(&t.ID,&t.Name,&t.Rate,&t.IsDefault)}else{err=r.dbReader.QueryRow(`SELECT id,name,rate,is_default FROM tax_rates WHERE is_active=true AND id=$1`,id).Scan(&t.ID,&t.Name,&t.Rate,&t.IsDefault)};return t,err}
func (r *quotationRepository) CanQuoteRequest(requestID,issuerID,customerID string)(bool,error){if requestID==""{return true,nil};var ok bool;err:=r.dbReader.QueryRow(`SELECT EXISTS(SELECT 1 FROM service_requests j WHERE j.id=$1 AND j.customer_id=$3 AND j.deleted_at IS NULL AND (j.target_isp_id=$2 OR j.target_technician_id=$2 OR j.assigned_isp_id=$2 OR j.assigned_technician_id=$2 OR EXISTS(SELECT 1 FROM service_request_applications a WHERE a.request_id=j.id AND a.applicant_id=$2)))`,requestID,issuerID,customerID).Scan(&ok);return ok,err}
